# Generated by Django 4.1.4 on 2023-03-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='datebirth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='gender',
        ),
    ]
