# Generated by Django 4.1.4 on 2023-08-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_datebirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/assets/img/icon/72x72.png', upload_to=''),
        ),
    ]
