# Generated by Django 4.1.4 on 2023-08-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticketmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
