# Generated by Django 4.1.4 on 2023-08-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rename_ticket_id_ticketmessage_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='user',
            new_name='to_user',
        ),
    ]
