# Generated by Django 4.1.3 on 2022-11-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='exercises',
        ),
    ]