# Generated by Django 4.1.4 on 2023-03-07 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0002_alter_exercise_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('cost', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'exercise_list',
            },
        ),
        migrations.CreateModel(
            name='ExerciseToUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'exercise_user',
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=255)),
                ('typecode', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'exercise_type',
            },
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AddField(
            model_name='exercisetousermodel',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercisetype'),
        ),
        migrations.AddField(
            model_name='exercisetousermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciselist',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercisetype'),
        ),
    ]
