# Generated by Django 4.1.3 on 2022-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('STR', 'Силовые'), ('CA', 'Кардио')], max_length=300),
        ),
    ]