# Generated by Django 4.1.4 on 2023-02-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STR', 'Силовые'), ('CA', 'Кардио')], max_length=300)),
                ('typecode', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(default=None, max_length=255)),
                ('cost', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
