# Generated by Django 4.1.4 on 2023-02-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exerciselist_delete_exercise'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exerciselist',
            table='exercise_list',
        ),
    ]
