# Generated by Django 4.1.4 on 2023-03-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exerciseuserresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetousermodel',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exerciselist'),
        ),
    ]
