# Generated by Django 4.1.4 on 2023-02-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exerciselist_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=255)),
                ('typecode', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'exercise_type',
            },
        ),
        migrations.RemoveField(
            model_name='exerciselist',
            name='typecode',
        ),
        migrations.AlterField(
            model_name='exerciselist',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercisetype'),
        ),
    ]
