# Generated by Django 4.1.4 on 2023-08-21 20:36

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_remove_exercisetousermodel_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselist',
            name='options',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Параметры'),
        ),
    ]
