# Generated by Django 4.1.3 on 2022-11-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorization', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=None),
        ),
    ]
