# Generated by Django 4.1.4 on 2023-03-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorization', '0007_alter_user_age_alter_user_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
