# Generated by Django 4.1.3 on 2022-11-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=255)),
                ('date_joined', models.CharField(default=None, max_length=255)),
                ('last_activity', models.CharField(default=None, max_length=255)),
                ('age', models.IntegerField(default=None, max_length=255)),
                ('weight', models.IntegerField(default=None, max_length=255)),
                ('avatar', models.ImageField(default=None, max_length=255, upload_to='')),
            ],
        ),
    ]
